### ISSUE TITLE
Некорректный селектор("invalid selector") в классе DashboardPage.

### ISSUE THREAD

**Issue by AleksandrZhuravel** [AleksandrZhuravel/aqa_homework2.4.1#1]
### Описание:
В классе **DashboardPage** был создан SelenideElement blockFirstCard, в котором был прописан css-селектор **"[data-test-id = 92df3f1c-a033-48e6-8390-206f6b1f56c0]"**. css-селектор был вставлен для обращения к полю с номером карты и кнопкой "Пополнить". Расположение элемента: класс DashboardPage, строка 11.

### Фактический результат:
После запуска авто-теста Gradle сообщил о его падении по причине возникновения ошибки **"org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified"** со ссылкой на селектор **"Element info: {Using=css selector, value=[data-test-id = 92df3f1c-a033-48e6-8390-206f6b1f56c0]}"**.

### Программное окружение:
* Устройство: Acer Aspire 5742ZG, ЦП - Intel Pentium P6200 2.13 GHZ
ОЗУ - 4 Gb
* ОС: Windows 7 Максимальная Service Pack 1 64-раздяная
* ПО: IntelliJ IDEA 2019.3.1(Community Edition)

### Скриншоты:
![Код](https://github.com/AleksandrZhuravel/trash2/blob/master/AQA_homework2.4.1/IDEAScreen.jpg?raw=true)

![Ошибка](https://github.com/AleksandrZhuravel/trash2/blob/master/AQA_homework2.4.1/MistakeScreen.jpg?raw=true)

![Тестируемый элемент](https://github.com/AleksandrZhuravel/trash2/blob/master/AQA_homework2.4.1/OpersScreen.jpg?raw=true)

### Ссылки:

[Java-класс DashboardPage](https://github.com/AleksandrZhuravel/aqa_homework2.4.1/blob/master/src/test/java/DashboardPage.java)

**Comment by coursar** [comment]
Должно быть вот так:
```java
private SelenideElement blockFirstCard = form.$("[data-test-id='92df3f1c-a033-48e6-8390-206f6b1f56c0']");
```

**Comment by coursar** [comment]
Без пробелов и в кавычках

**Comment by AleksandrZhuravel** [comment]
Ошибка устранена
